# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ksVgkpiiy4cYIlo2oElhRtC36ZDu9pEgubIYtsU+DndcwW0D73EPlKLhdiFm40xfxgS9x0F4NyjO6K565+GwK36Olmn8OapyuHiX3evZ7l6C3uDNjda7XOfsOnhnkUM+fQaixf4PVSt3C5Al9q18FGUjJvb4J1NyxgBEwSSev+QRjUThPV6tDCgq25Z6zGreuyVNLVVxVG0kAdcYxV7wVANTCuAqAxGuZsrnbrypsd5Me6YwXflU1Co9oUiRwSI8gCSHMdx/R6jNDYCvZrSlOSh+LHeMuQanIvs4vpXMAnchbZMgTnNUF0yrTU91jhxa4eNWkmuD/nBgEbuK9Wh0SHCZiuhKsxFzNyXnmIN+G25TNweo4awtzc1ySXWf3oHaXORdlfv5Dhjsnb86HImR6QeMsA9rHoPIk/W4VlUMsB4YWxIp+v1i3Zv60gTTP51NwP9ldsAQkPgMpjaWAher5RUx/QeNhIFNSfggIDAfqXVXGDPtdNuOtfjMZAoJOdqTWeGQsMTxQvVreLMaTFP0Lt7hmXrydSZq0QB9qfYg+Jv5DpYgM+d46jAVHcOPdAgH6Pox1QFD6cTl74wJr+AEszd3VgqpdWHQFtaOd+0ZdvvpQ+E66GwJIuzrPhmrWUACWOy16dHHh9+SRTzt2kJdBRK6YuTyUsS1aG4N/Rg/B/E="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
