appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: ksVgkpiiy4cYIlo2oElhRtC36ZDu9pEgubIYtsU+DndcwW0D73EPlKLhdiFm40xfxgS9x0F4NyjO6K565+GwK36Olmn8OapyuHiX3evZ7l6C3uDNjda7XOfsOnhnkUM+fQaixf4PVSt3C5Al9q18FGUjJvb4J1NyxgBEwSSev+QRjUThPV6tDCgq25Z6zGreuyVNLVVxVG0kAdcYxV7wVANTCuAqAxGuZsrnbrypsd5Me6YwXflU1Co9oUiRwSI8gCSHMdx/R6jNDYCvZrSlOSh+LHeMuQanIvs4vpXMAnchbZMgTnNUF0yrTU91jhxa4eNWkmuD/nBgEbuK9Wh0SHCZiuhKsxFzNyXnmIN+G25TNweo4awtzc1ySXWf3oHaXORdlfv5Dhjsnb86HImR6QeMsA9rHoPIk/W4VlUMsB4YWxIp+v1i3Zv60gTTP51NwP9ldsAQkPgMpjaWAher5RUx/QeNhIFNSfggIDAfqXVXGDPtdNuOtfjMZAoJOdqTWeGQsMTxQvVreLMaTFP0Lt7hmXrydSZq0QB9qfYg+Jv5DpYgM+d46jAVHcOPdAgH6Pox1QFD6cTl74wJr+AEszd3VgqpdWHQFtaOd+0ZdvvpQ+E66GwJIuzrPhmrWUACWOy16dHHh9+SRTzt2kJdBRK6YuTyUsS1aG4N/Rg/B/E=}
